#8b8tCore Version 1.6.4
AntiIllegal:
  Enabled: true
  EnableIllegalBlocksCleaner: true
  IllegalBlocks:
    - BEDROCK
    - BARRIER
    - COMMAND_BLOCK
    - CHAIN_COMMAND_BLOCK
    - REPEATING_COMMAND_BLOCK
    - STRUCTURE_BLOCK
    - STRUCTURE_VOID
    - JIGSAW
    - END_PORTAL_FRAME
    - NETHER_PORTAL
    - LIGHT
    - REINFORCED_DEEPSLATE
    - CHORUS_PLANT
    - TRIAL_SPAWNER
  MaxItemNameLength: 51
  IllegalItems:
    - 'BEDROCK'
    - 'BARRIER'
    - 'END_PORTAL_FRAME'
    - 'SPAWNER'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - '*SPAWN_EGG*'
    - '*COMMAND_BLOCK*'
    - 'KNOWLEDGE_BOOK'
    - 'DIRT_PATH'
    - 'FARMLAND'
    - 'REINFORCED_DEEPSLATE'
    - 'DEBUG_STICK'
    - 'LIGHT'
AnnouncementInterval: 90 # In seconds
AntiLagChest:
  enabled: true
  openCooldown: 1000L
  maxItemSizeAllowed: 50000 #size in bytes
NbtBanItemChecker:
  maxItemSizeAllowed: 50000 #size in bytes
ChatControl:
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 5
  #Blocked words
  Blocked:
    - 'Anar Anarchy'
    - '5b5t'
    - 'Deja de buscar un servidor y gastar dinero comprando kits y mejor unete al mejor servidor con Kits y Sorteos 100% Grati'
    - 'snowanarchy'
    - 'demonmc'
    - 'snowan'
    - 'Anar'
    - 'AnarAnarchy'
    - '.org'
    - 'EndPortal'
    - 'endportal'
    - 'NetherPortal'
    - 'netherportal'
    - '89.35.49.34:19175'
    - 'SurvivalCraft'
    - 'Joooin'
    - '.at'
    - 'Join 89,35,49,34:19175 Semi-Anarchy Bedrock'
    - 'Semi-Anarchy'
    - 'Join'
    - 'Entra'
    - '89,35'
    - 'JOIN'
    - 'fuck 8b8t'
    - 'mc.latinomc.tk'
    - 'AnarchyLatam.ploudos.me'
    - 'anarchyvn.net'
    - '9aJSETCQTr'
    - 'Nar6nCnS8T'
    - 'gg/9aJSETCQTr'
    - 'gg/Nar6nCnS8T'
    - 'lunecraft'
    - '3b3t.shock.gg'
    - 'snowаnarchy,оrg'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒｇ ｈａ ａｂｉｅｒｔｏ ｓｕｓ ｐｕｅｒｔａｓ ａ ｊｕｇａｄｏｒｅｓ ｅｓｐａñｏｌｅｓ ｙ ｉｎｇｌｅｓｅｓ， ｅｎｔｒａ ｙ ｄｉｓｆｒｕｔａ'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒg'
    - 'chad-sigma-topg'
    - '3b3t,shock,gg'
    - '3b3t'
    - '3B3T'
    - 'DeathAnarchy.nether-zone.com'
    - '9b9t'
    - 'discord'
  CommandWhitelist:
    - '/ic'
    - '/nc'
    - '/ignore'
    - '/unignore'
    - '/ignorelist'
    - '/togglechat'
    - '/toggledeathmsg'
    - '/msg'
    - '/message'
    - '/whisper'
    - '/tell'
    - '/w'
    - '/reply'
    - '/r'
    - '/home'
    - '/sethome'
    - '/delhome'
    - '/back'
    - '/help'
    - '/nick'
    - '/plugins'
    - '/pl'
    - '/kill'
    - '/jihad'
    - '/dupe'
    - '/stats'
    - '/tpa'
    - '/tpahere'
    - '/tpayes'
    - '/tpano'
    - '/tpacancel'
    - '/help'
    - '/worldstats'
    - '/stats'
    - '/discord'
    - '/matrix'
    - '/joindate'
    - '/jd'
    - '/seen'
    - '/echest'
    - '/voicechat'
    - '/vote'
    - '/tpsinfo'
    - '/ic'
    - '/itemcolor'
    - '/setcolor'
    - '/nc'
    - '/nickcolor'
    - '/namecolor'
    - '/nick'
    - '/setnick'
    - '/nickname'
    - '/rename'
    - '/hotspot'
    - '/sign'
    - '/togglejoinmessages'
    - '/shadowmute'
    - '/vanish'
    - '/clearentities'
    - '/suicide'
    - '/table'
    - '/tpatoggle'
    - '/tpaignore'
TPA:
  RequestTimeoutInMinutes: 5
TPS:
  Permissions:
    - '8b8tcore.tpsinfo'
TPAHOMERADIUS:
  # default max distance if no permission matches
  # override this value in your permissions plugin;
  # actual limits come from permissions like home.spawn.<n> and tpa.spawn.<n>
  default: 20000
Home:
  #Max homes a player can have
  MaxHomes: 5
#Voting requires VotifierPlus
#https://www.spigotmc.org/resources/votifierplus.74040/
Vote:
  Rewards:
    - 'lp user %s group add voter'
  # In days (0 days = no expiry)
  OfflineVoteExpirationDays: 7
  VoterRoleExpirationDays: 30
  LegacyPlayerDefaultDaysRemaining: 20
  EnableLegacyPlayerMigration: true
  ExpirationCommand: 'lp user %s group remove voter'
Patch:
  #Please note that elytra speed is in blocks per second.
  DefaultElytraMaxSpeedBlocksPerSecond: 128 #Max speed in blocks/second.
  TileEntitiesElytraMaxSpeedBlocksPerSecond: 64 #Max speed in a chunk with more than 128 tile entities.
  ChestLimitPerChunk: 192
  EntityPerChunk:
    CheckInterval: 1 #In minutes
    DefaultMax: 32 # -1 for unlimited default max
    EntitiesPerChunk:
      - 'wither::20'
      - 'boat::10'
      - 'falling_block::200'
      - 'dropped_item::100'
      - 'item_frame::130'
      - 'glow_item_frame::130'
Redstone:
    StrictTPS: 14 #The tps to start strictly monitoring redstone at
    StrictMaxVLS: 70 #How many redstone operations per second can happen in strict mode
    RegularMaxVLS: 20000 #How many redstone operations per second can happen in regular mode
Commands:
  Discord: '&3Join us on discord at&r&a https://discord.8b8t.me'
  Matrix: '&3Join us on matrix at&r&a https://matrix.8b8t.me'
OpUsersWhiteList:
  - 'Leee'
  - 'YoThisIsAnAltLOL'
  - 'cubebuilder_'
prefix: '&8[&98b&78t&8]'
viewdistance:
  default: 6
simulationdistance:
  default: 4
FrameDupe:
  enabled: false
  votersOnly: false
  dupeCooldown: 200L # Miliseconds
  limitItemsPerChunk: 18 # Dropped items
  probabilityPercentage: 100
ZombieDupe:
  enabled: true
  votersOnly: false
  dupeCooldown: 200L # Miliseconds
  limitItemsPerChunk: 18 # Dropped items
  probabilityPercentage: 100
  rottenFleshDropPercentage: 50
DonkeyDupe:
  enabled: true
  votersOnly: false
DupeCommand:
  enabled: false
  votersOnly: false
RestrictedMapIDs:
  - 1366
  - 1261
  - 1537
  - 1288
